import mongoose from 'mongoose';
import autopopulate from 'mongoose-autopopulate';
import mongooseToCsvQuotes from '../lib/mongoose-csv-quotes-fix';

import StudentData from './student-data';

const pointTrackerSchema = mongoose.Schema({
  date: Date,
  title: {
    type: String,
    required: true,
  },
  student: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Profile',
    required: true,
    autopopulate: { maxDepth: 1 },
  },
  mentor: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Profile',
    required: true,
    autopopulate: { maxDepth: 1 },
  },
  mentorIsSubstitute: Boolean, 
  subjects: [{
    subjectName: {
      type: String,
      required: true,
    },
    teacher: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: 'Profile', 
      autopopulate: true,
    },
    scoring: {
      excusedDays: Number,
      stamps: Number,
      halfStamps: Number,
      tutorials: Number,
    },
    grade: {
      type: String,
      enum: ['', 'A', 'B', 'C', 'D', 'F'],
    },
  }],
  communications: [
    {
      with: { type: String, default: 'Student' },
      role: { type: String, default: 'student' },
      faceToFace: { type: Boolean, default: false },
      digital: { type: Boolean, default: false },
      phone: { type: Boolean, default: false },
      other: { type: Boolean, default: false },
      notes: { type: String, default: '' },
    },
    {
      with: { type: String, default: 'Family' },
      role: { type: String, default: 'family' },
      faceToFace: { type: Boolean, default: false },
      digital: { type: Boolean, default: false },
      phone: { type: Boolean, default: false },
      other: { type: Boolean, default: false },
      notes: { type: String, default: '' },
    },
    {
      with: { type: String, default: 'Teacher' },
      role: { type: String, default: 'teacher' },
      faceToFace: { type: Boolean, default: false },
      digital: { type: Boolean, default: false },
      phone: { type: Boolean, default: false },
      other: { type: Boolean, default: false },
      notes: { type: String, default: '' },
    },
    {
      with: { type: String, default: 'Coach' },
      role: { type: String, default: 'coach' },
      faceToFace: { type: Boolean, default: false },
      digital: { type: Boolean, default: false },
      phone: { type: Boolean, default: false },
      other: { type: Boolean, default: false },
      notes: { type: String, default: '' },
    },
  ],
  oneTeam: {
    wednesdayCheckin: { type: Boolean, default: false },
    mentorMeal: { type: Boolean, default: false },
    sportsGame: { type: Boolean, default: false },
    communityEvent: { type: Boolean, default: false },
    iepSummerReview: { type: Boolean, default: false },
    other: { type: Boolean, default: false },
  },
  oneTeamNotes: { type: String, default: '' },
  pointSheetStatus: {
    turnedIn: { type: Boolean, default: true },
    lost: { type: Boolean, default: false },
    incomplete: { type: Boolean, default: false },
    absent: { type: Boolean, default: false },
    other: { type: Boolean, default: false },
  },
  pointSheetStatusNotes: { type: String, default: '' },
  earnedPlayingTime: String,
  mentorGrantedPlayingTime: String,
  synopsisComments: {
    mentorGrantedPlayingTimeComments: String, // required only if mentor overrides calculated playing time
    studentActionItems: String,
    sportsUpdate: String,
    additionalComments: String,
  },
}, { timestamps: true });
pointTrackerSchema.plugin(autopopulate);

const headers = ['title',
  'student.active',
  'student.firstName',
  'student.lastName',
  'student.email',
  'student.phone',
  'student.gender',
  'student.school',
  'mentorIsSubstitute',
  'mentor.firstName',
  'mentor.lastName',
  'comm.student.checkIn',
  'comm.student.raEvent',
  'comm.student.game',
  'comm.student.bcEmail',
  'comm.student.phoneText',
  'comm.student.notes',
  'comm.family.checkIn',
  'comm.family.raEvent',
  'comm.family.game',
  'comm.family.bcEmail',
  'comm.family.phoneText',
  'comm.family.meeting',
  'comm.family.notes',
  'comm.teacher.checkIn',
  'comm.teacher.raEvent',
  'comm.teacher.game',
  'comm.teacher.bcEmail',
  'comm.teacher.phoneText',
  'comm.teacher.notes',
  'comm.coach.checkIn',
  'comm.coach.raEvent',
  'comm.coach.game',
  'comm.coach.bcEmail',
  'comm.coach.phoneText',
  'comm.coach.notes',
  'status.turnedIn',
  'status.lost',
  'status.incomplete',
  'status.absent',
  'status.notes',
  'synopsisComments.extraPlayingTime',
  'synopsisComments.mentorGrantedPlayingTime',
  'synopsisComments.studentActionItems',
  'synopsisComments.sportsUpdate',
  'synopsisComments.additionalComments',
  'subject.1',
  'subject.1.excusedDays',
  'subject.1.stamps',
  'subject.1.halfStamp',
  'subjects.1.tutorials',
  'subjects.1.grade',
  'subject.2',
  'subject.2.excusedDays',
  'subject.2.stamps',
  'subject.2.halfStamp',
  'subjects.2.tutorials',
  'subjects.2.grade',  
  'subject.3',
  'subject.3.excusedDays',
  'subject.3.stamps',
  'subject.3.halfStamp',
  'subjects.3.tutorials',
  'subjects.3.grade',  
  'subject.4',
  'subject.4.excusedDays',
  'subject.4.stamps',
  'subject.4.halfStamp',
  'subjects.4.tutorials',
  'subjects.4.grade',  
  'subject.5',
  'subject.5.excusedDays',
  'subject.5.stamps',
  'subject.5.halfStamp',
  'subjects.5.tutorials',
  'subjects.5.grade',  
  'subject.6',
  'subject.6.excusedDays',
  'subject.6.stamps',
  'subject.6.halfStamp',
  'subjects.6.tutorials',
  'subjects.6.grade',  
  'subject.7',
  'subject.7.excusedDays',
  'subject.7.stamps',
  'subject.7.halfStamp',
  'subjects.7.tutorials',
  'subjects.7.grade',
  'subject.8',
  'subject.8.excusedDays',
  'subject.8.stamps',
  'subject.8.halfStamp',
  'subjects.8.tutorials',
  'subjects.8.grade',
];

const alias = {
  'comm.student.checkIn': 'communications[0].f2fCheckIn',
  'comm.student.raEvent': 'communications[0].f2fRaEvent',
  'comm.student.game': 'communications[0].f2fGameOrPractice',
  'comm.student.bcEmail': 'communications[0].basecampOrEmail',
  'comm.student.phoneText': 'communications[0].phoneOrText',
  'comm.student.notes': 'communications[0].notes',
  'comm.family.checkIn': 'communications[1].f2fCheckIn',
  'comm.family.raEvent': 'communications[1].f2fRaEvent',
  'comm.family.game': 'communications[1].f2fGameOrPractice',
  'comm.family.bcEmail': 'communications[1].basecampOrEmail',
  'comm.family.phoneText': 'communications[1].phoneOrText',
  'comm.family.meeting': 'communications[1].familyMeeting',
  'comm.family.notes': 'communications[1].notes',
  'comm.teacher.checkIn': 'communications[2].f2fCheckIn',
  'comm.teacher.raEvent': 'communications[2].f2fRaEvent',
  'comm.teacher.game': 'communications[2].f2fGameOrPractice',
  'comm.teacher.bcEmail': 'communications[2].basecampOrEmail',
  'comm.teacher.phoneText': 'communications[2].phoneOrText',
  'comm.teacher.notes': 'communications[2].notes',
  'comm.coach.checkIn': 'communications[3].f2fCheckIn',
  'comm.coach.raEvent': 'communications[3].f2fRaEvent',
  'comm.coach.game': 'communications[3].f2fGameOrPractice',
  'comm.coach.bcEmail': 'communications[3].basecampOrEmail',
  'comm.coach.phoneText': 'communications[3].phoneOrText',
  'comm.coach.notes': 'communications[3].notes',
  'status.turnedIn': 'pointSheetStatus.turnedIn',
  'status.lost': 'pointSheetStatus.lost',
  'status.incomplete': 'pointSheetStatus.incomplete',
  'status.absent': 'pointSheetStatus.absent',
  'status.notes': 'pointSheetStatus.notes',
  'subject.1': 'subjects[0].subjectName',
  'subject.1.excusedDays': 'subjects[0].scoring.excusedDays',
  'subject.1.stamps': 'subjects[0].scoring.stamps',
  'subject.1.halfStamp': 'subjects[0].scoring.halfStamp',
  'subject.1.tutorials': 'subjects[0].scoring.tutorials',
  'subject.1.grade': 'subjects[0].grade',
  'subject.2': 'subjects[1].subjectName',
  'subject.2.excusedDays': 'subjects[1].scoring.excusedDays',
  'subject.2.stamps': 'subjects[1].scoring.stamps',
  'subject.2.halfStamp': 'subjects[1].scoring.halfStamp',
  'subject.2.tutorials': 'subjects[1].scoring.tutorials',
  'subject.2.grade': 'subjects[1].grade',
  'subject.3': 'subjects[2].subjectName',
  'subject.3.excusedDays': 'subjects[2].scoring.excusedDays',
  'subject.3.stamps': 'subjects[2].scoring.stamps',
  'subject.3.halfStamp': 'subjects[2].scoring.halfStamp',
  'subject.3.tutorials': 'subjects[2].scoring.tutorials',
  'subject.3.grade': 'subjects[2].grade',
  'subject.4': 'subjects[3].subjectName',
  'subject.4.excusedDays': 'subjects[3].scoring.excusedDays',
  'subject.4.stamps': 'subjects[3].scoring.stamps',
  'subject.4.halfStamp': 'subjects[3].scoring.halfStamp',
  'subject.4.tutorials': 'subjects[3].scoring.tutorials',
  'subject.4.grade': 'subjects[3].grade',
  'subject.5': 'subjects[4].subjectName',
  'subject.5.excusedDays': 'subjects[4].scoring.excusedDays',
  'subject.5.stamps': 'subjects[4].scoring.stamps',
  'subject.5.halfStamp': 'subjects[4].scoring.halfStamp',
  'subject.5.tutorials': 'subjects[4].scoring.tutorials',
  'subject.5.grade': 'subjects[4].grade',
  'subject.6': 'subjects[5].subjectName',
  'subject.6.excusedDays': 'subjects[5].scoring.excusedDays',
  'subject.6.stamps': 'subjects[5].scoring.stamps',
  'subject.6.halfStamp': 'subjects[5].scoring.halfStamp',
  'subject.6.tutorials': 'subjects[5].scoring.tutorials',
  'subject.6.grade': 'subjects[5].grade',
  'subject.7': 'subjects[6].subjectName',
  'subject.7.excusedDays': 'subjects[6].scoring.excusedDays',
  'subject.7.stamps': 'subjects[6].scoring.stamps',
  'subject.7.halfStamp': 'subjects[6].scoring.halfStamp',
  'subject.7.tutorials': 'subjects[6].scoring.tutorials',
  'subject.7.grade': 'subjects[6].grade',
  'subject.8': 'subjects[7].subjectName',
  'subject.8.excusedDays': 'subjects[7].scoring.excusedDays',
  'subject.8.stamps': 'subjects[7].scoring.stamps',
  'subject.8.halfStamp': 'subjects[7].scoring.halfStamp',
  'subject.8.tutorials': 'subjects[7].scoring.tutorials',
  'subject.8.grade': 'subjects[7].grade',
};

pointTrackerSchema.plugin(mongooseToCsvQuotes, { show_headers: true, headers, alias });

pointTrackerSchema.post('save', async (tracker) => {
  const studentData = await StudentData.findOne({ student: tracker.student });
  // studentData may be null, particularly in the case of mocking test
  // data. If it is just ignore.
  if (studentData) studentData.lastPointTracker = tracker._id;
  return studentData ? studentData.save() : undefined;
});

const skipInit = process.env.NODE_ENV === 'development';
export default mongoose.model('PointTracker', pointTrackerSchema, 'pointTrackers', skipInit);
